---
title: "Social Referencing and Uncertainty"
author: "Emily & Mike"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    number_sections: true
---

<style type="text/css">
body, td {
   font-size: 14px;
}
code {
  font-size: 11px;
}
pre {
  font-size: 11px;
}
</style>

Data analysis of social referencing and uncertainty study.

# Data preprocessing

Preliminaries.

```{r echo=FALSE}
rm(list=ls())
knitr::opts_chunk$set(fig.width=8, fig.height=5, 
                      echo=TRUE, warning=FALSE, message=FALSE, cache=TRUE)
suppressPackageStartupMessages(c("dplyr","langcog","tidyr","ggplot2","lme4"))
library(langcog)
library(dplyr)
library(ggplot2)
library(rjson)
library(stringr)
library(tidyr)
library(lme4)
library(xtable)
library(knitr)
library(markdown)
theme_set(theme_bw())
```

Read in files and consolidate to the same directory. 

Coder 1

```{r}
files <- dir("../data/coder_1/")
d.raw_c1 <- data.frame()

for (f in files) {
  jf <- paste("../data/coder_1/",f,sep="")
  jd <- read.csv(jf)
  id <- data.frame(SID = f,
                   line = jd$phase.ordinal,
                   phase = as.numeric(jd$phase.1_2_3_4),
                   phase_onset_c1 = jd$phase.onset,
                   phase_offset_c1 = jd$phase.offset, 
                   num_looks_c1 = jd$reference.num_looks,
                   exclude_c1 = jd$reference.exclude.)
  d.raw_c1 <- bind_rows(d.raw_c1, id)
}

d.raw_c1$SID <- str_replace(d.raw_c1$SID, ".csv", "")

```

Coder 2

```{r}
files <- dir("../data/coder_2/")
d.raw_c2 <- data.frame()

for (f in files) {
  jf <- paste("../data/coder_2/",f,sep="")
  jd <- read.csv(jf)
  id <- data.frame(SID = f,
                   line = jd$phase.ordinal,
                   phase = as.numeric(jd$phase.1_2_3_4),
                   phase_onset_c2 = jd$phase.onset,
                   phase_offset_c2 = jd$phase.offset, 
                   num_looks_c2 = jd$reference.num_looks,
                   exclude_c2 = jd$reference.exclude.)
  d.raw_c2 <- bind_rows(d.raw_c2, id)
}

d.raw_c2$SID <- str_replace(d.raw_c2$SID, ".csv", "")
```

```{r}
soc_ref_rel <- d.raw_c1 %>%
  left_join(d.raw_c2) %>%
  mutate(phase_onset_diff = phase_onset_c1- phase_onset_c2) %>%
  mutate(phase_offset_diff = phase_offset_c1 - phase_offset_c2) %>%
  mutate(phase_onset_bin_100 = abs(phase_onset_diff)<100) %>%
  mutate(phase_offset_bin_100 = abs(phase_offset_diff)<100) %>%
  mutate(phase_onset_bin_200 = abs(phase_onset_diff)<200) %>%
  mutate(phase_offset_bin_200 = abs(phase_offset_diff)<200) 

summary(soc_ref_rel$phase_onset_diff)
summary(soc_ref_rel$phase_offset_diff)
summary(soc_ref_rel$phase_onset_bin_100)
summary(soc_ref_rel$phase_offset_bin_100)
summary(soc_ref_rel$phase_onset_bin_200)
summary(soc_ref_rel$phase_offset_bin_200)
```

